config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  resources :books, only: [ :index, :new, :create ]

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
  end

  def create
    Book.create(book_params)
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.haml
%h1 Good afternoon Alex! Welcome!

%table
  %thead
    %tr
      %td Name
      %td Author

  %tbody
    - @books.each do |book|
      %tr
        %td= book.name
        %td= book.author

.create_new_book
  = link_to 'Create new book', new_book_path, id: 'create_new_book'
.dinner
  = link_to 'Dinner', '#', id: 'dinner'

app/views/books/new.html.haml
%h1 Welcome to create a new book!

= form_for Book.new do |f|
  .name
    = f.label :name
    = f.text_field :name
  .author
    = f.label :author
    = f.text_field :author
  = f.submit 'Create'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>